apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nhysn0bkd-python
  janus-idp.io/tekton: nhysn0bkd-python
  backstage.io/kubernetes-id: nhysn0bkd-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nhysn0bkd-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
