apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nhysn0bkd-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-01a56a759d.7p73.p3.openshiftapps.com/rhtap/rhtap-qe:964a0e07687c5bd65cfc90bc07e7a73ef7be1dcf@sha256:9621994e660f1f7c939a6086b34681f40ad56de60ff0666926472ae577a1ae6e
          name: container-image
